ALTER TYPE "PackageType" ADD VALUE IF NOT EXISTS 'DROP_IN_CLASS';
ALTER TYPE "PackageType" ADD VALUE IF NOT EXISTS 'DROP_IN_CAMP';
ALTER TYPE "PackageType" ADD VALUE IF NOT EXISTS 'DROP_IN_CAMP_EXTENDED';
